/* AUTOGENERATED by scripts/generate-tokens.mts from contracts/design-tokens.json.
   DO NOT EDIT BY HAND — run `pnpm --filter @intown/frontend run generate:tokens`. */

export const lightTokens = {
  "bg": "#FAF7F2",
  "surface": "#FFFFFF",
  "text": "#1C1917",
  "text-secondary": "#57534E",
  "text-tertiary": "#79716B",
  "border": "#E7E5E4",
  "primary": "#2563EB",
  "on-primary": "#FFFFFF",
  "primary-pressed": "#1E40AF",
  "on-primary-pressed": "#FFFFFF",
  "link": "#1D4ED8",
  "jade": "#047857",
  "on-jade": "#FFFFFF",
  "jade-chip-bg": "#D1FAE5",
  "jade-chip-text": "#065F46",
  "terracotta": "#C2410C",
  "on-terracotta": "#FFFFFF",
  "terracotta-chip-bg": "#FFEDD5",
  "terracotta-chip-text": "#9A3412",
  "warning": "#F59E0B",
  "on-warning": "#451A03",
  "error": "#B91C1C",
  "on-error": "#FFFFFF",
  "success": "#15803D",
  "on-success": "#FFFFFF",
  "selected-ring": "#2563EB",
  "focus": "#2563EB",
} as const;

/**
 * Dark palette.
 *
 * TEXT-ROLE-ONLY: `jade`, `terracotta`, `warning`, `error` are foreground
 * (text/icon) values here — see the `dark.*-on-bg` role:large pairs in
 * contracts/design-tokens.json. Their `on-*` companions are not overridden
 * for dark, so using them as background fills (e.g. `bg-terracotta` with
 * `text-on-terracotta`) fails contrast. For filled surfaces in dark use the
 * dedicated fill tokens: `terracotta-fill` (with `on-terracotta`). `error-large`
 * is the large-text/icon error variant for dark.
 */
export const darkTokens = {
  "bg": "#0C0A09",
  "surface": "#1C1917",
  "text": "#FAFAF9",
  "text-secondary": "#D6D3D1",
  "text-tertiary": "#BFB8B2",
  "border": "#292524",
  "primary": "#60A5FA",
  "on-primary": "#0C0A09",
  "primary-pressed": "#3B82F6",
  "on-primary-pressed": "#FFFFFF",
  "link": "#93C5FD",
  "jade": "#34D399",
  "jade-chip-bg": "#064E3B",
  "jade-chip-text": "#A7F3D0",
  "terracotta": "#FDBA74",
  "terracotta-fill": "#C2410C",
  "on-terracotta": "#FFFFFF",
  "terracotta-chip-bg": "#7C2D12",
  "terracotta-chip-text": "#FED7AA",
  "warning": "#FBBF24",
  "error": "#FCA5A5",
  "error-large": "#F87171",
  "success": "#4ADE80",
  "selected-ring": "#2563EB",
  "focus": "#60A5FA",
} as const;

export const tokens = { light: lightTokens, dark: darkTokens } as const;

export type TokenName = keyof typeof lightTokens;

/**
 * OKLCH-derived tonal ramps (50→900) for the five InTown seeds, plus the
 * proposed CVD lightness-separated pin-category ramp. Deterministically
 * generated from the seeds/anchors — see scripts/oklch.mts and
 * docs/contract-change-P01-pin-ramp.md.
 */
export const rampTokens = {
  blue: {
    "50": "#F1F6FF",
    "100": "#DCE8FF",
    "200": "#B7D0FF",
    "300": "#8FB5FF",
    "400": "#6196FF",
    "500": "#3170F9",
    "600": "#1855DD",
    "700": "#003BBF",
    "800": "#002A91",
    "900": "#001A64",
  },
  sand: {
    "50": "#F8F5F0",
    "100": "#EAE7E2",
    "200": "#D2CFCA",
    "300": "#B8B5B1",
    "400": "#9C9995",
    "500": "#7E7B77",
    "600": "#676460",
    "700": "#504E4A",
    "800": "#3B3935",
    "900": "#272521",
  },
  ink: {
    "50": "#F9F5F2",
    "100": "#EBE7E4",
    "200": "#D3CECC",
    "300": "#B9B5B2",
    "400": "#9D9996",
    "500": "#7F7B78",
    "600": "#676461",
    "700": "#514E4B",
    "800": "#3C3836",
    "900": "#282422",
  },
  terracotta: {
    "50": "#FFF3EF",
    "100": "#FFE0D6",
    "200": "#FFBEA9",
    "300": "#FF9574",
    "400": "#F06C40",
    "500": "#CD4B1C",
    "600": "#AE3600",
    "700": "#892900",
    "800": "#671C00",
    "900": "#461000",
  },
  jade: {
    "50": "#DEFFEF",
    "100": "#A1FFD7",
    "200": "#89E6BF",
    "300": "#6FCBA6",
    "400": "#51AE8A",
    "500": "#2D8F6D",
    "600": "#017756",
    "700": "#005D43",
    "800": "#004530",
    "900": "#002D1F",
  },
} as const;

export const pinRamp = {
  "photo": "#F1772E",
  "viewpoint": "#0071A0",
  "art": "#EFA81C",
  "history": "#6407CD",
  "museum": "#4581FF",
  "food": "#004F38",
} as const;

export type RampName = keyof typeof rampTokens;
export type RampStep = keyof (typeof rampTokens)['blue'];
export type PinCategory = keyof typeof pinRamp;
