/* AUTOGENERATED by scripts/generate-tokens.mts from contracts/design-tokens.json.
   DO NOT EDIT BY HAND — run `pnpm --filter @intown/frontend run generate:tokens`. */

export const lightTokens = {
  "bg": "#FAF7F2",
  "surface": "#FFFFFF",
  "text": "#1C1917",
  "text-secondary": "#57534E",
  "text-tertiary": "#79716B",
  "border": "#E7E5E4",
  "primary": "#2563EB",
  "on-primary": "#FFFFFF",
  "primary-pressed": "#1E40AF",
  "on-primary-pressed": "#FFFFFF",
  "link": "#1D4ED8",
  "jade": "#047857",
  "on-jade": "#FFFFFF",
  "jade-chip-bg": "#D1FAE5",
  "jade-chip-text": "#065F46",
  "terracotta": "#C2410C",
  "on-terracotta": "#FFFFFF",
  "terracotta-chip-bg": "#FFEDD5",
  "terracotta-chip-text": "#9A3412",
  "warning": "#F59E0B",
  "on-warning": "#451A03",
  "error": "#B91C1C",
  "on-error": "#FFFFFF",
  "success": "#15803D",
  "on-success": "#FFFFFF",
  "selected-ring": "#2563EB",
  "focus": "#2563EB",
} as const;

/**
 * Dark palette.
 *
 * TEXT-ROLE-ONLY: `jade`, `terracotta`, `warning`, `error` are foreground
 * (text/icon) values here — see the `dark.*-on-bg` role:large pairs in
 * contracts/design-tokens.json. Their `on-*` companions are not overridden
 * for dark, so using them as background fills (e.g. `bg-terracotta` with
 * `text-on-terracotta`) fails contrast. For filled surfaces in dark use the
 * dedicated fill tokens: `terracotta-fill` (with `on-terracotta`). `error-large`
 * is the large-text/icon error variant for dark.
 */
export const darkTokens = {
  "bg": "#0C0A09",
  "surface": "#1C1917",
  "text": "#FAFAF9",
  "text-secondary": "#D6D3D1",
  "text-tertiary": "#BFB8B2",
  "border": "#292524",
  "primary": "#60A5FA",
  "on-primary": "#0C0A09",
  "primary-pressed": "#3B82F6",
  "on-primary-pressed": "#FFFFFF",
  "link": "#93C5FD",
  "jade": "#34D399",
  "jade-chip-bg": "#064E3B",
  "jade-chip-text": "#A7F3D0",
  "terracotta": "#FDBA74",
  "terracotta-fill": "#C2410C",
  "on-terracotta": "#FFFFFF",
  "terracotta-chip-bg": "#7C2D12",
  "terracotta-chip-text": "#FED7AA",
  "warning": "#FBBF24",
  "error": "#FCA5A5",
  "error-large": "#F87171",
  "success": "#4ADE80",
  "selected-ring": "#2563EB",
  "focus": "#60A5FA",
} as const;

export const tokens = { light: lightTokens, dark: darkTokens } as const;

export type TokenName = keyof typeof lightTokens;
