# generated by datamodel-codegen:
#   filename:  AccountLink.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class AccountLink(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    provider: str
    provider_account_id: str
    type: str
