# generated by datamodel-codegen:
#   filename:  AccountExport.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from .Consent import Consent
from .TasteProfile import TasteProfile
from .TravelerProfile import TravelerProfile
from .User import User


class AccountExport(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    consents: list[Consent]
    taste_profiles: list[TasteProfile]
    traveler_profile: TravelerProfile | None
    user: User
