# generated by datamodel-codegen:
#   filename:  Badge.json

from __future__ import annotations

from typing import Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict


class Badge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: str
    created_at: AwareDatetime
    description: str | None
    id: UUID
    name: str
    rule: dict[str, Any]
