# generated by datamodel-codegen:
#   filename:  BBox.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, confloat


class BBox(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    max_lat: confloat(ge=-90.0, le=90.0)
    max_lng: confloat(ge=-180.0, le=180.0)
    min_lat: confloat(ge=-90.0, le=90.0)
    min_lng: confloat(ge=-180.0, le=180.0)
