# generated by datamodel-codegen:
#   filename:  CardOpenedPayload.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict, conint


class CardOpenedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    dwell_ms: conint(ge=0, le=9007199254740991)
    poi_id: UUID
    trip_place_id: UUID | None = None
