# generated by datamodel-codegen:
#   filename:  City.json

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict

from .BBox import BBox


class BrainStatus(StrEnum):
    cold = 'cold'
    building = 'building'
    warm = 'warm'
    stale = 'stale'


class City(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    bbox: BBox
    brain_status: BrainStatus
    country_code: str | None
    created_at: AwareDatetime
    id: UUID
    name: str
    pmtiles_path: str | None
    updated_at: AwareDatetime
    warmed_at: AwareDatetime | None
