# generated by datamodel-codegen:
#   filename:  CityBrief.json

from __future__ import annotations

from typing import Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict


class CityBrief(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    city_id: UUID
    content: dict[str, Any]
    generated_at: AwareDatetime
    id: UUID
    language: str
