# generated by datamodel-codegen:
#   filename:  ClosedReportedPayload.json

from __future__ import annotations

from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict


class ClosedReportedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    poi_id: UUID
    reported_at: AwareDatetime
    trip_place_id: UUID | None = None
