# generated by datamodel-codegen:
#   filename:  Consent.json

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict


class ConsentType(StrEnum):
    personalization_learning = 'personalization_learning'
    location_derived_signals = 'location_derived_signals'
    marketing = 'marketing'


class Consent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    consent_type: ConsentType
    granted: bool
    granted_at: AwareDatetime
    id: UUID
    policy_version: str
    revoked_at: AwareDatetime | None
    user_id: UUID
