# generated by datamodel-codegen:
#   filename:  Coordinate.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, confloat


class Coordinate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    lat: confloat(ge=-90.0, le=90.0)
    lng: confloat(ge=-180.0, le=180.0)
