# generated by datamodel-codegen:
#   filename:  Correction.json

from __future__ import annotations

from enum import StrEnum
from typing import Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, conint


class Status(StrEnum):
    pending = 'pending'
    accepted = 'accepted'
    rejected = 'rejected'


class Correction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    confirmations: conint(ge=0, le=9007199254740991)
    created_at: AwareDatetime
    fact_id: UUID
    id: UUID
    proposed_value: Any
    reporter_id: UUID
    status: Status
