# generated by datamodel-codegen:
#   filename:  DayFeedbackPayload.json

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import BaseModel, ConfigDict, conint


class Sentiment(StrEnum):
    positive = 'positive'
    neutral = 'neutral'
    negative = 'negative'


class DayFeedbackPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    day_index: conint(ge=0, le=9007199254740991)
    note: str | None = None
    rating: conint(ge=1, le=5) | None = None
    sentiment: Sentiment | None = None
    trip_city_id: UUID
