# generated by datamodel-codegen:
#   filename:  Event.json

from __future__ import annotations

from typing import Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict


class Event(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    algo_version: str | None
    consent_flag: bool
    event_data: dict[str, Any]
    event_type: str
    id: UUID
    occurred_at: AwareDatetime
    trip_id: UUID | None
    user_id: UUID | None
