# generated by datamodel-codegen:
#   filename:  Fact.json

from __future__ import annotations

from enum import StrEnum
from typing import Any
from uuid import UUID

from pydantic import (AnyUrl, AwareDatetime, BaseModel, ConfigDict, confloat,
                      conint)


class EntityKind(StrEnum):
    poi = 'poi'
    city = 'city'


class SourceKind(StrEnum):
    llm_research = 'llm_research'
    osm = 'osm'
    wikidata = 'wikidata'
    official_site = 'official_site'
    open_data = 'open_data'
    advisory = 'advisory'
    web_review = 'web_review'
    user_correction = 'user_correction'


class Status(StrEnum):
    active = 'active'
    superseded = 'superseded'
    disputed = 'disputed'
    rejected = 'rejected'


class Fact(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attribute: str
    confidence: confloat(ge=0.0, le=1.0)
    corroboration_count: conint(ge=0, le=9007199254740991)
    entity_id: UUID
    entity_kind: EntityKind
    id: UUID
    observed_at: AwareDatetime
    source_kind: SourceKind
    source_url: AnyUrl | None
    status: Status
    value: Any
