# generated by datamodel-codegen:
#   filename:  GoNowTriggeredPayload.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict


class GoNowTriggeredPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    poi_id: UUID
    trip_city_id: UUID
