# generated by datamodel-codegen:
#   filename:  IntercityLeg.json

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict


class Mode(StrEnum):
    train = 'train'
    bus = 'bus'
    flight = 'flight'
    car = 'car'
    ferry = 'ferry'
    other = 'other'


class IntercityLeg(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    arr_place: str | None
    arr_time: AwareDatetime | None
    booking_ref: str | None
    dep_place: str | None
    dep_time: AwareDatetime | None
    from_trip_city_id: UUID | None
    id: UUID
    mode: Mode
    to_trip_city_id: UUID | None
    trip_id: UUID
