# generated by datamodel-codegen:
#   filename:  ItemStats.json

from __future__ import annotations

from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, conint


class ItemStats(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    algo_version: str
    id: UUID
    n: conint(ge=0, le=9007199254740991)
    poi_id: UUID
    posterior: float
    segment: str | None
    sum_score: float
    updated_at: AwareDatetime
