# generated by datamodel-codegen:
#   filename:  ListShownPayload.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict

from .RankedItem import RankedItem


class ListShownPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ranking: list[RankedItem]
    trip_city_id: UUID
