# generated by datamodel-codegen:
#   filename:  ListFinalizedPayload.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict


class ListFinalizedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ordered_place_ids: list[UUID]
    trip_city_id: UUID
