# generated by datamodel-codegen:
#   filename:  ModerationAction.json

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict


class Decision(StrEnum):
    pending = 'pending'
    no_action = 'no_action'
    content_removed = 'content_removed'
    content_demoted = 'content_demoted'
    rejected = 'rejected'


class TargetKind(StrEnum):
    review = 'review'
    correction = 'correction'
    poi = 'poi'
    fact = 'fact'
    import_ = 'import'


class ModerationAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    created_at: AwareDatetime
    decided_at: AwareDatetime | None
    decision: Decision
    id: UUID
    moderator_id: UUID | None
    notice: str
    noticed_at: AwareDatetime
    reporter_id: UUID | None
    statement_of_reasons: str | None
    target_id: UUID
    target_kind: TargetKind
