# generated by datamodel-codegen:
#   filename:  Money.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, constr


class Money(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    amount: float
    currency: constr(pattern=r'^[A-Z]{3}$', min_length=3, max_length=3)
