# generated by datamodel-codegen:
#   filename:  MustDoLockedPayload.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict


class MustDoLockedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    poi_id: UUID
    trip_place_id: UUID
