# generated by datamodel-codegen:
#   filename:  NarrationCompletedPayload.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict, conint


class NarrationCompletedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    completed: bool
    language: str
    listened_ms: conint(ge=0, le=9007199254740991) | None = None
    poi_id: UUID
