# generated by datamodel-codegen:
#   filename:  NarrationGeneratedPayload.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict


class NarrationGeneratedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    language: str
    poi_id: UUID
