# generated by datamodel-codegen:
#   filename:  PlaceRemovedPayload.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict, conint


class PlaceRemovedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    poi_id: UUID
    rank: conint(ge=0, le=9007199254740991)
    trip_place_id: UUID
