# generated by datamodel-codegen:
#   filename:  PlaceVote.json

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict


class Vote(StrEnum):
    up = 'up'
    down = 'down'


class PlaceVote(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    created_at: AwareDatetime
    id: UUID
    trip_place_id: UUID
    user_id: UUID
    vote: Vote
