# generated by datamodel-codegen:
#   filename:  PlaceSkippedPayload.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict


class PlaceSkippedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    poi_id: UUID
    stop_id: UUID | None = None
    trip_place_id: UUID | None = None
