# generated by datamodel-codegen:
#   filename:  PlaceReorderedPayload.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict, conint


class PlaceReorderedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    from_rank: conint(ge=0, le=9007199254740991)
    list_after: list[UUID]
    list_before: list[UUID]
    poi_id: UUID
    to_rank: conint(ge=0, le=9007199254740991)
    trip_place_id: UUID
