# generated by datamodel-codegen:
#   filename:  PlaceVisitedPayload.json

from __future__ import annotations

from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, conint


class PlaceVisitedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    arrival_at: AwareDatetime | None = None
    departure_at: AwareDatetime | None = None
    dwell_ms: conint(ge=0, le=9007199254740991) | None = None
    poi_id: UUID
    stop_id: UUID | None = None
    trip_place_id: UUID | None = None
