# generated by datamodel-codegen:
#   filename:  PlanRegeneratedPayload.json

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import BaseModel, ConfigDict


class Reason(StrEnum):
    initial = 'initial'
    manual_edit = 'manual_edit'
    reconfigure = 'reconfigure'
    regenerated = 'regenerated'
    go_now = 'go_now'
    closed_now = 'closed_now'
    restore = 'restore'


class PlanRegeneratedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    plan_revision_id: UUID | None = None
    reason: Reason
    trip_city_id: UUID
