# generated by datamodel-codegen:
#   filename:  PlanRevision.json

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, conint


class Reason(StrEnum):
    initial = 'initial'
    manual_edit = 'manual_edit'
    reconfigure = 'reconfigure'
    regenerated = 'regenerated'
    go_now = 'go_now'
    closed_now = 'closed_now'
    restore = 'restore'


class PlanRevision(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    created_at: AwareDatetime
    created_by: UUID
    id: UUID
    reason: Reason
    revision_index: conint(ge=0, le=9007199254740991)
    trip_city_id: UUID
