# generated by datamodel-codegen:
#   filename:  Poi.json

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, confloat

from .Coordinate import Coordinate
from .PoiAccessibility import PoiAccessibility
from .PoiExternalIds import PoiExternalIds
from .SourceRef import SourceRef


class Category(StrEnum):
    SIGHT = 'SIGHT'
    MUSEUM = 'MUSEUM'
    VIEWPOINT = 'VIEWPOINT'
    PARK_NATURE = 'PARK_NATURE'
    ENTERTAINMENT = 'ENTERTAINMENT'
    NIGHTLIFE = 'NIGHTLIFE'
    SHOPPING = 'SHOPPING'
    RESTAURANT = 'RESTAURANT'
    CAFE = 'CAFE'
    OTHER = 'OTHER'


class CoordResolution(StrEnum):
    unverified = 'unverified'
    approximate = 'approximate'
    verified = 'verified'


class CoordVerifiedBy(StrEnum):
    open_data = 'open_data'
    cross_referenced = 'cross_referenced'
    first_traveler_gps = 'first_traveler_gps'


class IndoorOutdoor(StrEnum):
    indoor = 'indoor'
    outdoor = 'outdoor'
    mixed = 'mixed'


class Poi(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    accessibility: PoiAccessibility
    aliases: list[str]
    category: Category
    city_id: UUID
    coord: Coordinate | None
    coord_confidence: confloat(ge=0.0, le=1.0) | None
    coord_resolution: CoordResolution
    coord_verified_by: CoordVerifiedBy | None
    created_at: AwareDatetime
    external_ids: PoiExternalIds
    id: UUID
    indoor_outdoor: IndoorOutdoor
    name: str
    prominence: confloat(ge=0.0, le=1.0)
    source_refs: list[SourceRef]
    updated_at: AwareDatetime
