# generated by datamodel-codegen:
#   filename:  PoiAccessibility.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class PoiAccessibility(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    stairs: bool | None
    stroller: bool | None
    wheelchair: bool | None
