# generated by datamodel-codegen:
#   filename:  PoiExternalIds.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class PoiExternalIds(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    google_place_id: str | None
    osm_id: str | None
    wikidata_id: str | None
