# generated by datamodel-codegen:
#   filename:  PoiEnrichment.json

from __future__ import annotations

from typing import Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict


class PoiEnrichment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    audio_path: str | None
    generated_at: AwareDatetime
    id: UUID
    language: str
    poi_id: UUID
    scripts: dict[str, Any] | None
    significance: str
