# generated by datamodel-codegen:
#   filename:  PoiGeoObservation.json

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, confloat


class SourceKind(StrEnum):
    osm = 'osm'
    wikidata = 'wikidata'
    commons_photo = 'commons_photo'
    flickr_photo = 'flickr_photo'
    source_maplink = 'source_maplink'
    visual_recognition = 'visual_recognition'
    google_fallback = 'google_fallback'
    first_traveler_gps = 'first_traveler_gps'


class PoiGeoObservation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    accuracy_m: confloat(ge=0.0) | None
    confidence: confloat(ge=0.0, le=1.0)
    expires_at: AwareDatetime | None
    id: UUID
    lat: confloat(ge=-90.0, le=90.0)
    lng: confloat(ge=-180.0, le=180.0)
    observed_at: AwareDatetime
    poi_id: UUID
    source_kind: SourceKind
