# generated by datamodel-codegen:
#   filename:  PoiHours.json

from __future__ import annotations

from datetime import date
from uuid import UUID

from pydantic import BaseModel, ConfigDict, conint, constr


class PoiHours(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    closes: constr(pattern=r'^([01]\d|2[0-3]):[0-5]\d$') | None
    day_of_week: conint(ge=0, le=6) | None
    id: UUID
    is_24h: bool
    is_closed: bool
    is_holiday_exception: bool
    note: str | None
    opens: constr(pattern=r'^([01]\d|2[0-3]):[0-5]\d$') | None
    poi_id: UUID
    valid_from: date | None
    valid_to: date | None
