# generated by datamodel-codegen:
#   filename:  PriceCorrectedPayload.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict

from .Money import Money


class PriceCorrectedPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fact_id: UUID | None = None
    old_price: Money | None = None
    poi_id: UUID
    proposed_price: Money
