# generated by datamodel-codegen:
#   filename:  RankedItem.json

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import BaseModel, ConfigDict, conint


class Tier(StrEnum):
    must_see = 'must_see'
    want = 'want'
    maybe = 'maybe'


class RankedItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    poi_id: UUID
    rank: conint(ge=0, le=9007199254740991)
    score: float | None = None
    tier: Tier | None = None
    trip_place_id: UUID
