# generated by datamodel-codegen:
#   filename:  ResearchRequest.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict


class ResearchRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    force_refresh: bool | None = None
    trip_city_id: UUID | None = None
