# generated by datamodel-codegen:
#   filename:  ResearchStageLog.json

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, ConfigDict


class Stage(StrEnum):
    brain_check = 'brain_check'
    intake = 'intake'
    candidates = 'candidates'
    ground = 'ground'


class ResearchStageLog(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    message: str
    stage: Stage
    type: Literal['stage_log']
