# generated by datamodel-codegen:
#   filename:  ResearchCandidateScored.json

from __future__ import annotations

from enum import StrEnum
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict


class Tier(StrEnum):
    must_see = 'must_see'
    want = 'want'
    maybe = 'maybe'


class ResearchCandidateScored(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    justification: str | None = None
    poi_id: UUID
    score: float
    tier: Tier | None = None
    type: Literal['candidate_scored']
