# generated by datamodel-codegen:
#   filename:  ResearchCompleted.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, conint


class ResearchCompleted(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    candidate_count: conint(ge=0, le=9007199254740991)
    longlist_ready: bool
    trip_city_id: UUID
    type: Literal['research_completed']
