# generated by datamodel-codegen:
#   filename:  ResearchPlaceFound.json

from __future__ import annotations

from enum import StrEnum
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict


class Category(StrEnum):
    SIGHT = 'SIGHT'
    MUSEUM = 'MUSEUM'
    VIEWPOINT = 'VIEWPOINT'
    PARK_NATURE = 'PARK_NATURE'
    ENTERTAINMENT = 'ENTERTAINMENT'
    NIGHTLIFE = 'NIGHTLIFE'
    SHOPPING = 'SHOPPING'
    RESTAURANT = 'RESTAURANT'
    CAFE = 'CAFE'
    OTHER = 'OTHER'


class ResearchPlaceFound(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    category: Category
    name: str
    poi_id: UUID
    type: Literal['place_found']
