# generated by datamodel-codegen:
#   filename:  ResearchResult.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict, conint


class ResearchResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    candidate_count: conint(ge=0, le=9007199254740991)
    longlist_ready: bool
    trip_city_id: UUID
