# generated by datamodel-codegen:
#   filename:  ResearchStageCompleted.json

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, ConfigDict


class Stage(StrEnum):
    brain_check = 'brain_check'
    intake = 'intake'
    candidates = 'candidates'
    ground = 'ground'


class ResearchStageCompleted(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    stage: Stage
    summary: str | None = None
    type: Literal['stage_completed']
