# generated by datamodel-codegen:
#   filename:  ResearchStreamMessage.json

from __future__ import annotations

from pydantic import Field, RootModel

from .ResearchCandidateScored import ResearchCandidateScored
from .ResearchCompleted import ResearchCompleted
from .ResearchPlaceFound import ResearchPlaceFound
from .ResearchStageCompleted import ResearchStageCompleted
from .ResearchStageLog import ResearchStageLog
from .ResearchStageStarted import ResearchStageStarted
from .SseError import SseError


class ResearchStreamMessage(RootModel[ResearchStageStarted | ResearchStageLog | ResearchPlaceFound | ResearchCandidateScored | ResearchStageCompleted | ResearchCompleted | SseError]):
    root: ResearchStageStarted | ResearchStageLog | ResearchPlaceFound | ResearchCandidateScored | ResearchStageCompleted | ResearchCompleted | SseError = Field(..., title='ResearchStreamMessage')
