# generated by datamodel-codegen:
#   filename:  Review.json

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, conint


class Status(StrEnum):
    pending = 'pending'
    published = 'published'
    removed = 'removed'


class Review(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    created_at: AwareDatetime
    id: UUID
    poi_id: UUID
    rating: conint(ge=1, le=5)
    status: Status
    text: str | None
    updated_at: AwareDatetime
    user_id: UUID
    verified_visit: bool
