# generated by datamodel-codegen:
#   filename:  ScenicLeg.json

from __future__ import annotations

from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, confloat

from .SourceRef import SourceRef


class ScenicLeg(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    city_id: UUID
    confidence: confloat(ge=0.0, le=1.0)
    created_at: AwareDatetime
    description: str
    from_poi_id: UUID | None
    id: UUID
    source_refs: list[SourceRef]
    to_poi_id: UUID | None
