# generated by datamodel-codegen:
#   filename:  SessionMeta.json

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict


class SessionMeta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expires: AwareDatetime
