# generated by datamodel-codegen:
#   filename:  SolverRequest.json

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import BaseModel, ConfigDict, conint

from .SolverCandidate import SolverCandidate
from .SolverDay import SolverDay
from .SolverTravelEdge import SolverTravelEdge


class DefaultMode(StrEnum):
    walk = 'walk'
    transit = 'transit'
    drive = 'drive'
    bike = 'bike'
    ferry = 'ferry'


class SolverRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    candidates: list[SolverCandidate]
    days: list[SolverDay]
    default_mode: DefaultMode
    time_budget_ms: conint(le=9007199254740991, gt=0)
    travel_matrix: list[SolverTravelEdge]
    trip_city_id: UUID
