# generated by datamodel-codegen:
#   filename:  SolverTravelEdge.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field, confloat, conint


class Mode(StrEnum):
    walk = 'walk'
    transit = 'transit'
    drive = 'drive'
    bike = 'bike'
    ferry = 'ferry'


class SolverTravelEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    from_: str = Field(..., alias='from')
    meters: confloat(ge=0.0)
    mode: Mode
    seconds: conint(ge=0, le=9007199254740991)
    to: str
