# generated by datamodel-codegen:
#   filename:  SolverDay.json

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict, confloat, conint

from .SolverAnchor import SolverAnchor


class SolverDay(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    day_index: conint(ge=0, le=9007199254740991)
    end_anchor: SolverAnchor | None
    end_deadline: AwareDatetime | None
    start: SolverAnchor
    start_time: AwareDatetime
    walking_budget_m: confloat(ge=0.0) | None
