# generated by datamodel-codegen:
#   filename:  SolverDaySchedule.json

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict, confloat, conint

from .SolverScheduledStop import SolverScheduledStop


class SolverDaySchedule(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    day_index: conint(ge=0, le=9007199254740991)
    ends_at: AwareDatetime | None
    stops: list[SolverScheduledStop]
    walking_m: confloat(ge=0.0)
