# generated by datamodel-codegen:
#   filename:  SolverScheduledStop.json

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, conint

from .SolverTravelLeg import SolverTravelLeg


class StopKind(StrEnum):
    poi = 'poi'
    meal = 'meal'
    break_ = 'break'


class SolverScheduledStop(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    arrive: AwareDatetime
    day_index: conint(ge=0, le=9007199254740991)
    depart: AwareDatetime
    ord: conint(ge=0, le=9007199254740991)
    poi_id: UUID | None
    stop_kind: StopKind
    travel_from_prev: SolverTravelLeg | None
