# generated by datamodel-codegen:
#   filename:  SolverOpeningWindow.json

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict, conint


class SolverOpeningWindow(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    closes: AwareDatetime
    day_index: conint(ge=0, le=9007199254740991)
    opens: AwareDatetime
