# generated by datamodel-codegen:
#   filename:  SolverResponse.json

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import BaseModel, ConfigDict, conint

from .SolverDaySchedule import SolverDaySchedule


class Status(StrEnum):
    optimal = 'optimal'
    feasible = 'feasible'
    infeasible = 'infeasible'
    timeout = 'timeout'


class SolverResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    days: list[SolverDaySchedule]
    objective_value: float | None
    solve_ms: conint(ge=0, le=9007199254740991)
    status: Status
    trip_city_id: UUID
    unscheduled_poi_ids: list[UUID]
