# generated by datamodel-codegen:
#   filename:  SolverAnchor.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict

from .Coordinate import Coordinate


class SolverAnchor(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    coord: Coordinate
    label: str | None
    node: str
    poi_id: UUID | None
