# generated by datamodel-codegen:
#   filename:  SolverCandidate.json

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import BaseModel, ConfigDict, conint

from .Coordinate import Coordinate
from .SolverOpeningWindow import SolverOpeningWindow


class Category(StrEnum):
    SIGHT = 'SIGHT'
    MUSEUM = 'MUSEUM'
    VIEWPOINT = 'VIEWPOINT'
    PARK_NATURE = 'PARK_NATURE'
    ENTERTAINMENT = 'ENTERTAINMENT'
    NIGHTLIFE = 'NIGHTLIFE'
    SHOPPING = 'SHOPPING'
    RESTAURANT = 'RESTAURANT'
    CAFE = 'CAFE'
    OTHER = 'OTHER'


class IndoorOutdoor(StrEnum):
    indoor = 'indoor'
    outdoor = 'outdoor'
    mixed = 'mixed'


class SolverCandidate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    category: Category
    coord: Coordinate
    est_duration_min: conint(le=9007199254740991, gt=0)
    indoor_outdoor: IndoorOutdoor
    must_do: bool
    node: str
    poi_id: UUID
    priority: float
    windows: list[SolverOpeningWindow]
