# generated by datamodel-codegen:
#   filename:  SolverTravelLeg.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, confloat, conint


class Mode(StrEnum):
    walk = 'walk'
    transit = 'transit'
    drive = 'drive'
    bike = 'bike'
    ferry = 'ferry'


class SolverTravelLeg(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    meters: confloat(ge=0.0)
    mode: Mode
    seconds: conint(ge=0, le=9007199254740991)
