# generated by datamodel-codegen:
#   filename:  SourceRef.json

from __future__ import annotations

from enum import StrEnum

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict


class SourceKind(StrEnum):
    llm_research = 'llm_research'
    osm = 'osm'
    wikidata = 'wikidata'
    official_site = 'official_site'
    open_data = 'open_data'
    advisory = 'advisory'
    web_review = 'web_review'
    user_correction = 'user_correction'


class SourceRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    external_id: str | None = None
    observed_at: AwareDatetime | None = None
    source_kind: SourceKind
    source_url: AnyUrl | None = None
