# generated by datamodel-codegen:
#   filename:  SseError.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict


class SseError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: str
    fatal: bool
    message: str
    type: Literal['error']
