# generated by datamodel-codegen:
#   filename:  Stop.json

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, conint


class StopKind(StrEnum):
    poi = 'poi'
    meal = 'meal'
    break_ = 'break'


class Stop(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    day_index: conint(ge=0, le=9007199254740991)
    end_time: AwareDatetime | None
    est_duration: conint(le=9007199254740991, gt=0) | None
    id: UUID
    ord: conint(ge=0, le=9007199254740991)
    plan_revision_id: UUID
    poi_id: UUID | None
    start_time: AwareDatetime | None
    stop_kind: StopKind
    trip_city_id: UUID
