# generated by datamodel-codegen:
#   filename:  TasteProfile.json

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, conint


class BudgetTier(StrEnum):
    budget = 'budget'
    moderate = 'moderate'
    comfort = 'comfort'
    luxury = 'luxury'


class Pace(StrEnum):
    relaxed = 'relaxed'
    moderate = 'moderate'
    packed = 'packed'


class TasteProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    anti_preferences: list[str]
    budget_tier: BudgetTier
    created_at: AwareDatetime
    dietary: list[str]
    hard_exclusions: list[str]
    id: UUID
    interests: list[str]
    pace: Pace
    user_id: UUID
    version: conint(ge=0, le=9007199254740991)
