# generated by datamodel-codegen:
#   filename:  TicketLink.json

from __future__ import annotations

from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict


class TicketLink(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    added_at: AwareDatetime | None
    added_by: UUID | None
    label: str | None
    url: AnyUrl
