# generated by datamodel-codegen:
#   filename:  TransitPass.json

from __future__ import annotations

from datetime import date
from typing import Any
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict

from .Money import Money


class TransitPass(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    as_of: date | None
    city_id: UUID
    coverage: dict[str, Any] | None
    created_at: AwareDatetime
    description: str | None
    id: UUID
    name: str
    price: Money | None
    source_url: AnyUrl | None
    validity: str | None
