# generated by datamodel-codegen:
#   filename:  TravelerProfile.json

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, constr


class AgeBand(StrEnum):
    field_18 = '<18'
    field_18_25 = '18-25'
    field_26_44 = '26-44'
    field_45_64 = '45-64'
    field_65_ = '65+'


class Mobility(StrEnum):
    full = 'full'
    limited = 'limited'
    wheelchair = 'wheelchair'
    stroller = 'stroller'


class TravelerProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    age_band: AgeBand
    created_at: AwareDatetime
    currency: constr(pattern=r'^[A-Z]{3}$', min_length=3, max_length=3)
    eu_residency: bool
    id: UUID
    languages: list[str]
    mobility: Mobility
    student: bool
    updated_at: AwareDatetime
    user_id: UUID
