# generated by datamodel-codegen:
#   filename:  TripDocument.json

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict


class ParentKind(StrEnum):
    TRIP = 'TRIP'
    TRIP_CITY = 'TRIP_CITY'
    INTERCITY_LEG = 'INTERCITY_LEG'
    STOP = 'STOP'


class TripDocument(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    content_type: str | None
    created_at: AwareDatetime
    filename: str | None
    id: UUID
    member_ids: list[UUID]
    parent_id: UUID
    parent_kind: ParentKind
    storage_path: str
    trip_id: UUID
    uploaded_by: UUID
