# generated by datamodel-codegen:
#   filename:  TripMember.json

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict


class Role(StrEnum):
    owner = 'owner'
    editor = 'editor'
    viewer = 'viewer'


class TripMember(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    joined_at: AwareDatetime
    role: Role
    trip_id: UUID
    user_id: UUID
