# generated by datamodel-codegen:
#   filename:  TripPlace.json

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, conint


class State(StrEnum):
    suggested = 'suggested'
    kept = 'kept'
    removed = 'removed'
    must_do = 'must_do'


class TripPlace(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    added_by: UUID
    created_at: AwareDatetime
    est_duration: conint(le=9007199254740991, gt=0) | None
    id: UUID
    poi_id: UUID
    position: str
    state: State
    trip_city_id: UUID
    updated_at: AwareDatetime
