# generated by datamodel-codegen:
#   filename:  TripInvite.json

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict


class Role(StrEnum):
    owner = 'owner'
    editor = 'editor'
    viewer = 'viewer'


class TripInvite(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: str
    created_at: AwareDatetime
    created_by: UUID
    expires_at: AwareDatetime
    id: UUID
    revoked: bool
    role: Role
    trip_id: UUID
