# generated by datamodel-codegen:
#   filename:  Trip.json

from __future__ import annotations

from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict


class Trip(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    created_at: AwareDatetime
    id: UUID
    name: str
    owner_id: UUID
    updated_at: AwareDatetime
