# generated by datamodel-codegen:
#   filename:  TripCity.json

from __future__ import annotations

from datetime import date
from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, conint


class TripCity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    accommodation: dict[str, Any] | None
    arrive: date
    city_id: UUID
    depart: date
    id: UUID
    ord: conint(ge=0, le=9007199254740991)
    start_defaults: dict[str, Any] | None
    trip_id: UUID
