# generated by datamodel-codegen:
#   filename:  UserBadge.json

from __future__ import annotations

from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict


class UserBadge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    awarded_at: AwareDatetime
    badge_id: UUID
    id: UUID
    trip_id: UUID | None
    user_id: UUID
