# generated by datamodel-codegen:
#   filename:  User.json

from __future__ import annotations

from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, EmailStr


class User(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    created_at: AwareDatetime
    display_name: str | None
    email: EmailStr | None
    handle: str | None
    id: UUID
    locale: str | None
    updated_at: AwareDatetime
