# generated by datamodel-codegen:
#   filename:  UserPrefProfile.json

from __future__ import annotations

from typing import Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict


class UserPrefProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    algo_version: str
    preference_summary: str | None
    updated_at: AwareDatetime
    user_id: UUID
    weights: dict[str, Any]
