# generated by datamodel-codegen:
#   filename:  VoteCastPayload.json

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import BaseModel, ConfigDict


class Vote(StrEnum):
    up = 'up'
    down = 'down'


class VoteCastPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    poi_id: UUID
    trip_place_id: UUID
    vote: Vote
