# generated by datamodel-codegen:
#   filename:  WantToGo.json

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict


class Status(StrEnum):
    saved = 'saved'
    discarded = 'discarded'
    resolved = 'resolved'


class WantToGo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    city: str | None
    creator_handle: str | None
    id: UUID
    poi_id: UUID | None
    saved_at: AwareDatetime
    source_url: AnyUrl | None
    status: Status
    unresolved_name: str | None
    user_id: UUID
