/**
 * Generates the frontend design-token layer from the frozen contract
 * `contracts/design-tokens.json`:
 *   - ui-tokens/tokens.css  — CSS custom properties (:root light, @media dark,
 *                             [data-theme='dark'] / [data-theme='light'] overrides)
 *   - ui-tokens/tokens.ts   — typed const mirror of the light/dark palettes
 *
 * Output is deterministic (fixed key order from the source JSON, fixed
 * formatting) so re-running produces a byte-identical file — the CI/`generate`
 * idempotency check depends on this. This file is the ONLY writer of ui-tokens/*.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const frontendDir = resolve(scriptDir, '..');
const tokensJsonPath = resolve(frontendDir, '..', 'contracts', 'design-tokens.json');
const outDir = resolve(frontendDir, 'ui-tokens');

interface DesignTokens {
  light: Record<string, string>;
  dark: Record<string, string>;
}

const tokens = JSON.parse(readFileSync(tokensJsonPath, 'utf8')) as DesignTokens;
const { light, dark } = tokens;

const HEADER_CSS =
  '/* AUTOGENERATED by scripts/generate-tokens.mts from contracts/design-tokens.json.\n' +
  '   DO NOT EDIT BY HAND — run `pnpm --filter @intown/frontend run generate:tokens`. */\n';

const HEADER_TS =
  '/* AUTOGENERATED by scripts/generate-tokens.mts from contracts/design-tokens.json.\n' +
  '   DO NOT EDIT BY HAND — run `pnpm --filter @intown/frontend run generate:tokens`. */\n';

function varBlock(palette: Record<string, string>, indent: string): string {
  return Object.entries(palette)
    .map(([name, value]) => `${indent}--${name}: ${value};`)
    .join('\n');
}

const css =
  HEADER_CSS +
  '\n' +
  `:root {\n${varBlock(light, '  ')}\n}\n` +
  '\n' +
  '@media (prefers-color-scheme: dark) {\n' +
  `  :root:not([data-theme='light']) {\n${varBlock(dark, '    ')}\n  }\n` +
  '}\n' +
  '\n' +
  `:root[data-theme='dark'] {\n${varBlock(dark, '  ')}\n}\n` +
  '\n' +
  `:root[data-theme='light'] {\n${varBlock(light, '  ')}\n}\n`;

function tsObject(name: string, palette: Record<string, string>): string {
  const body = Object.entries(palette)
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
    .join('\n');
  return `export const ${name} = {\n${body}\n} as const;\n`;
}

const ts =
  HEADER_TS +
  '\n' +
  tsObject('lightTokens', light) +
  '\n' +
  tsObject('darkTokens', dark) +
  '\n' +
  'export const tokens = { light: lightTokens, dark: darkTokens } as const;\n' +
  '\n' +
  'export type TokenName = keyof typeof lightTokens;\n';

mkdirSync(outDir, { recursive: true });
writeFileSync(resolve(outDir, 'tokens.css'), css);
writeFileSync(resolve(outDir, 'tokens.ts'), ts);

console.log('Generated ui-tokens/tokens.css and ui-tokens/tokens.ts');
