/**
 * Generates the frontend design-token layer from the frozen contract
 * `contracts/design-tokens.json`:
 *   - ui-tokens/tokens.css  — CSS custom properties (:root light, @media dark,
 *                             [data-theme='dark'] / [data-theme='light'] overrides)
 *                             plus a trailing :root block of OKLCH-derived ramps.
 *   - ui-tokens/tokens.ts   — typed const mirror of the light/dark palettes,
 *                             plus the generated ramp + pin-ramp exports.
 *
 * Output is deterministic (fixed key order from the source JSON, fixed
 * formatting) so re-running produces a byte-identical file — the CI/`generate`
 * idempotency check depends on this. This file is the ONLY writer of ui-tokens/*.
 *
 * The flat light/dark blocks are emitted verbatim (byte-identical to prior
 * output); the OKLCH ramp blocks are appended after them. The ramp math lives
 * in ./oklch.mts (pure, tested by tests/oklch.test.ts).
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { generateRamps, generatePinRamp, SEEDS } from './oklch.mts';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const frontendDir = resolve(scriptDir, '..');
const tokensJsonPath = resolve(frontendDir, '..', 'contracts', 'design-tokens.json');
const outDir = resolve(frontendDir, 'ui-tokens');

interface DesignTokens {
  light: Record<string, string>;
  dark: Record<string, string>;
  map: { pins: { anchors: Record<string, string> } };
}

const tokens = JSON.parse(readFileSync(tokensJsonPath, 'utf8')) as DesignTokens;
const { light, dark } = tokens;
const pinAnchors = tokens.map.pins.anchors;

const HEADER_CSS =
  '/* AUTOGENERATED by scripts/generate-tokens.mts from contracts/design-tokens.json.\n' +
  '   DO NOT EDIT BY HAND — run `pnpm --filter @intown/frontend run generate:tokens`. */\n';

const HEADER_TS =
  '/* AUTOGENERATED by scripts/generate-tokens.mts from contracts/design-tokens.json.\n' +
  '   DO NOT EDIT BY HAND — run `pnpm --filter @intown/frontend run generate:tokens`. */\n';

function varBlock(palette: Record<string, string>, indent: string): string {
  return Object.entries(palette)
    .map(([name, value]) => `${indent}--${name}: ${value};`)
    .join('\n');
}

// OKLCH-derived ramps (deterministic; math + tests in ./oklch.mts).
const ramps = generateRamps();
const pins = generatePinRamp(pinAnchors);
const seedNames = Object.keys(SEEDS) as (keyof typeof SEEDS)[];

const rampCss =
  '\n' +
  '/* OKLCH-derived palette ramps (P01, §17.1). Per seed: hue+chroma held while\n' +
  '   OKLCH lightness is stepped 50→900, chroma gamut-clamped to sRGB. The pin\n' +
  '   ramp is the proposed CVD lightness-separated set — a contract-change request,\n' +
  '   see docs/contract-change-P01-pin-ramp.md. Generated by scripts/oklch.mts. */\n' +
  ':root {\n' +
  seedNames
    .map(
      (seed) =>
        `  /* ${seed} */\n` +
        ramps[seed].map((color) => `  --${seed}-${color.step}: ${color.hex};`).join('\n'),
    )
    .join('\n\n') +
  '\n\n  /* pin categories (proposed) */\n' +
  pins.map((pin) => `  --pin-${pin.category}: ${pin.hex};`).join('\n') +
  '\n}\n';

function rampTsObject(): string {
  const seedBodies = seedNames
    .map((seed) => {
      const entries = ramps[seed]
        .map((color) => `    ${JSON.stringify(String(color.step))}: ${JSON.stringify(color.hex)},`)
        .join('\n');
      return `  ${seed}: {\n${entries}\n  },`;
    })
    .join('\n');
  return `export const rampTokens = {\n${seedBodies}\n} as const;\n`;
}

function pinRampTsObject(): string {
  const entries = pins
    .map((pin) => `  ${JSON.stringify(pin.category)}: ${JSON.stringify(pin.hex)},`)
    .join('\n');
  return `export const pinRamp = {\n${entries}\n} as const;\n`;
}

const RAMP_TS_DOC =
  '/**\n' +
  ' * OKLCH-derived tonal ramps (50→900) for the five InTown seeds, plus the\n' +
  ' * proposed CVD lightness-separated pin-category ramp. Deterministically\n' +
  ' * generated from the seeds/anchors — see scripts/oklch.mts and\n' +
  ' * docs/contract-change-P01-pin-ramp.md.\n' +
  ' */';

const rampTs =
  RAMP_TS_DOC +
  '\n' +
  rampTsObject() +
  '\n' +
  pinRampTsObject() +
  '\n' +
  'export type RampName = keyof typeof rampTokens;\n' +
  "export type RampStep = keyof (typeof rampTokens)['blue'];\n" +
  'export type PinCategory = keyof typeof pinRamp;\n';

const css =
  HEADER_CSS +
  '\n' +
  `:root {\n${varBlock(light, '  ')}\n}\n` +
  '\n' +
  '@media (prefers-color-scheme: dark) {\n' +
  `  :root:not([data-theme='light']) {\n${varBlock(dark, '    ')}\n  }\n` +
  '}\n' +
  '\n' +
  `:root[data-theme='dark'] {\n${varBlock(dark, '  ')}\n}\n` +
  '\n' +
  `:root[data-theme='light'] {\n${varBlock(light, '  ')}\n}\n` +
  rampCss;

function tsObject(name: string, palette: Record<string, string>, doc?: string): string {
  const body = Object.entries(palette)
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
    .join('\n');
  const jsdoc = doc ? `${doc}\n` : '';
  return `${jsdoc}export const ${name} = {\n${body}\n} as const;\n`;
}

const DARK_DOC =
  '/**\n' +
  ' * Dark palette.\n' +
  ' *\n' +
  ' * TEXT-ROLE-ONLY: `jade`, `terracotta`, `warning`, `error` are foreground\n' +
  ' * (text/icon) values here — see the `dark.*-on-bg` role:large pairs in\n' +
  ' * contracts/design-tokens.json. Their `on-*` companions are not overridden\n' +
  " * for dark, so using them as background fills (e.g. `bg-terracotta` with\n" +
  ' * `text-on-terracotta`) fails contrast. For filled surfaces in dark use the\n' +
  ' * dedicated fill tokens: `terracotta-fill` (with `on-terracotta`). `error-large`\n' +
  ' * is the large-text/icon error variant for dark.\n' +
  ' */';

const ts =
  HEADER_TS +
  '\n' +
  tsObject('lightTokens', light) +
  '\n' +
  tsObject('darkTokens', dark, DARK_DOC) +
  '\n' +
  'export const tokens = { light: lightTokens, dark: darkTokens } as const;\n' +
  '\n' +
  'export type TokenName = keyof typeof lightTokens;\n' +
  '\n' +
  rampTs;

mkdirSync(outDir, { recursive: true });
writeFileSync(resolve(outDir, 'tokens.css'), css);
writeFileSync(resolve(outDir, 'tokens.ts'), ts);

console.log('Generated ui-tokens/tokens.css and ui-tokens/tokens.ts');
